### ISSUE TITLE
maven fails to build on linux (Ubuntu 12.04)

### ISSUE THREAD

**Issue by psibre** [marytts/marytts-txt2wav#1]
```
$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building txt2wav 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ txt2wav ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /local/steiner/workspace/marytts-txt2wav/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ txt2wav ---
[INFO] Compiling 1 source file to /local/steiner/workspace/marytts-txt2wav/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.890s
[INFO] Finished at: Wed May 27 20:38:18 CEST 2015
[INFO] Final Memory: 29M/1931M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project txt2wav: Compilation failure
[ERROR] /local/steiner/workspace/marytts-txt2wav/src/main/java/de/dfki/mary/Txt2Wav.java:[69,37] error: incompatible types
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by psibre** [comment]
fixed in 97129b1eda8c797a550b6935fb0709375218c1c7
